services:
  # rasp:
  #   build: ./rasp
  #   ports:
  #     - "${RASP_PORT}:8000"
  #   devices:
  #     - /dev/video0:/dev/video0
  #   restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/config:/app/config
      - ./backend/data:/app/data
      - .env:/.env
    networks:
      - wateringcat_network
    hostname: backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:8501"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - wateringcat_network
    restart: unless-stopped

networks:
  wateringcat_network:
    driver: bridge